import Head from "next/head";
import { Roboto } from "@next/font/google";
import Futux from "@/components/Futux";
import Resume from "@/components/Resume";
import Coverletter from "@/components/Coverletter";
import {useState} from 'react';
import { buttonArr } from "@/components/constants";

export default function Home() {
  const [next, setNext] =useState(1)
  return (
    <>
      <Head>
        <title>AI Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-start min-h-screen py-2">
        {next === 1 && 
        <>
        <div className="flex flex-col items-center justify-center px-4 py-2">
            <h1 className="text-4xl md:text-6xl font-bold">
              AI Resume, Coverletter Generator
              <span className="text-4xl md:text-6xl font-bold text-blue-600">
                .
              </span>
            </h1>
            <p className="mt-3 text-2xl">
              select one
            </p>
      </div>
        <div className="flex flex-row justify-evenly items-center w-1/2 h-[30vh]">
          
          {buttonArr.filter((item)=> item.name !== 'Home').map(({id, name})=>{
            return(
              <button 
              className="bg-blue-500 rounded-lg text-white w-[100px] h-[100px]" key={id}
              onClick={()=>{
                if (name === 'Resume') {
                  setNext(2)
                }
                else if (name === 'Cover letter') {
                  setNext(3)
                }
                else if (name === 'Other') {
                  setNext(4)
                }
              }}
              >{name}</button>
            )
          })}
        </div>
        </>
        }
        {next === 2 && <Resume setNext={setNext}/>}
        {next === 3 && <Coverletter setNext={setNext}/>}
        {next === 4 && <Futux setNext={setNext}/>}
      </main>
    </>
  );
}
